In [2]:
import numpy as np

In [23]:
# Exercise 1
# Qn 1
# Array Comparison

a = np.array([1,2,3,7])
b = np.array([3,1,5,7])

print("Greater than Check: ",np.greater(a,b))
print("Greater than or Equal to Check: ",np.greater_equal(a,b))
print("Lesser than Check: ",np.less(a,b))
print("Lesser than or Equal to Check: ",np.less_equal(a,b))
print("Equal to Check: ",np.equal(a,b),"\n")


Greater than Check:  [False  True False False]
Greater than or Equal to Check:  [False  True False  True]
Lesser than Check:  [ True False  True False]
Lesser than or Equal to Check:  [ True False  True  True]
Equal to Check:  [False False False  True] 



In [35]:
# Exercise 1
# Qn 2
# Create an Array of All Even Integers from 30 to 70

x=np.arange(30,71,2)

print("Array of All Even Integers from 30 to 70:",x)

Array of All Even Integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [132]:
# Exercise 1
# Qn 3
# Create a 3x3 identity Matrix

print("3x3 identity Matrix: ")
np.identity(3,dtype = int)

3x3 identity Matrix: 


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [41]:
# Exercise 1
# Qn 4 
# Create a vector with values from 0 to 20
# Change the Sign of numbers from 9 to 15

x=np.arange(0,21)
a=np.array(x)
a[9:16] *= -1
print(a)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [74]:
# Exercise 1
# Qn 5
# Create a 5x5 zero Matrix
# Elements of main diagonal = 1,2,3,4,5

print("5x5 zero Matrix","\n")
a=np.zeros([5,5], dtype = int)
print(a,"\n","\n")
print("After Changing Diagonal Elements","\n")
np.fill_diagonal(a,[1,2,3,4,5])
print(a)

5x5 zero Matrix 

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 
 

After Changing Diagonal Elements 

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [91]:
# Exercise 1
# Qn 6
# Compute sum of all elements
# sum of each column and each row in a given array

x=np.array([[1,2,3,4],[2,3,4,5]])
print("Given Matrix: ","\n",x,"\n")
print("Total Sum: ",np.sum(x))
print("Sum of Columns: ",np.sum(x,axis=0))
print("Sum of Rows: ",np.sum(x,axis=1))

Given Matrix:  
 [[1 2 3 4]
 [2 3 4 5]] 

Total Sum:  24
Sum of Columns:  [3 5 7 9]
Sum of Rows:  [10 14]


In [135]:
# Exercise 1
# Qn 7
# Save A given array to a text file & load it

a = np.array([1,2,3,4,5],dtype = int) 
print("Original Array: ",a,"\n")
np.savetxt('/home/exam1/Desktop/HIRAN_S1MCA/test.txt',a)
b = np.loadtxt('/home/exam1/Desktop/HIRAN_S1MCA/test.txt') 
print("Array after loading: ",b)

Original Array:  [1 2 3 4 5] 

Array after loading:  [1. 2. 3. 4. 5.]


In [108]:
# Exercise 1
# Qn 8
# check whether 2 arrays are equal element wise or not

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

eql = np.equal(a,b)
if eql.all():
    print("All Element of the 2 Arrays are Equal")
elif eql.any():
    print("Only some elements of the 2 Arrays are equal")
else:
    print("None of the elements of the 2 Arrays are equal ")

None of the elements of the 2 Arrays are equal 


In [133]:
# Exercise 1
# Qn 9
# Create 4x4 array with random values
# Create new array from the given array swapping 1st and last rows

a = np.random.randint(10, size=(4, 4))
print("Original Random array: ","\n",a,'\n')
a[[0,3]] = a[[3,0]]
print("Random array swapped: ","\n",a,'\n')

Original Random array:  
 [[3 6 3 7]
 [0 9 1 9]
 [5 7 2 4]
 [9 2 2 6]] 

Random array swapped:  
 [[9 2 2 6]
 [0 9 1 9]
 [5 7 2 4]
 [3 6 3 7]] 



In [131]:
# Exercise 1
# Qn 10
# Multiply 2 arrays of the same size element by element

a = np.array([1,2,3,4])
b = np.array([5,4,3,2])
print(" Array 1: ",a,"\n","Array 2: ",b)
prod=np.multiply(a,b)
print(" Multiplying the given arrays element wise: ",prod)

 Array 1:  [1 2 3 4] 
 Array 2:  [5 4 3 2]
 Multiplying the given arrays element wise:  [5 8 9 8]
