In [1]:
#Exercise 2
#numpy matrix operations
import numpy as np

In [92]:
#create 2 Matrices (read values from user)

r = int(input("Enter no. of rows"))
l1 = []
l2 = []
print("Enter the values for matrix 1\n")
for i in range(r):
    a = np.array(list(map(int, input("Enter the numbers: ").split())))
    l1.append(a)
print("\n Enter the values for matrix 2\n")
for i in range(r):
    b = np.array(list(map(int, input("Enter the numbers: ").split())))
    l2.append(b)
m1=np.matrix(l1)
m2=np.matrix(l2)
print("\n Matrix 1: \n",m1)
print("\n Matrix 2: \n",m2)

Enter no. of rows2
Enter the values for matrix 1

Enter the numbers1 2
Enter the numbers2 4

 Enter the values for matrix 2

Enter the numbers5 6
Enter the numbers8 9

 Matrix 1: 
 [[1 2]
 [2 4]]

 Matrix 2: 
 [[5 6]
 [8 9]]


In [49]:
# 1. Dot Product

print("Dot Product: ")
np.dot(m1,m2)

Dot Product: 


matrix([[2178, 2057],
        [4840, 4719]])

In [103]:
# 2. Transpose

print("Transpose of matrix 1 \n",np.transpose(m1),"\n\nTranspose of matrix 2\n",np.transpose(m2))

Transpose of matrix 1 
 [[1 2]
 [2 4]] 

Transpose of matrix 2
 [[5 8]
 [6 9]]


In [66]:
# 3. Trace
# Return the sum along diagonals of the array.

print("Trace of matrix 1\n",np.trace(m1),"\n\nTrace of matrix 2\n",np.trace(m2))

Trace of matrix 1
 44 

Trace of matrix 2
 121


In [100]:
# 4. rank

print("Rank of matrix 1\n",np.linalg.matrix_rank(m1),"\n\nRank of matrix 2\n",np.linalg.matrix_rank(m2))

Rank of matrix 1
 1 

Rank of matrix 2
 2


In [96]:
# 5. Determinant

print("Determinant of matrix 1\n",np.linalg.det(m1),"\n\nDeterminant of matrix 2\n",np.linalg.det(m2))

Determinant of matrix 1
 0.0 

Determinant of matrix 2
 -2.9999999999999996


In [98]:
# 6. Inverse

if np.linalg.det(m1) != 0 :
    print("Inverse of matrix 1\n",np.linalg.inv(m1))
else:
    print("Matrix 1 is singluar \n")

if np.linalg.det(m2) != 0 :
    print("Inverse of matrix 2\n",np.linalg.inv(m2))
else:
    print("Matrix 2 is singluar ")
    
#print("Inverse of matrix 1\n",np.linalg.inv(m1),"\n\nInverse of matrix 2\n",np.linalg.inv(m2))

Matrix 1 is singluar 

Inverse of matrix 2
 [[-3.          2.        ]
 [ 2.66666667 -1.66666667]]


In [106]:
# 7. Eigen Values and Eigen Vectors

print("Eigen values of matrix 1\n",np.linalg.eig(m1),"\n\nEigen values of matrix 2\n",np.linalg.eig(m2))

Eigen values of matrix 1
 EigResult(eigenvalues=array([0., 5.]), eigenvectors=matrix([[-0.89442719, -0.4472136 ],
        [ 0.4472136 , -0.89442719]])) 

Eigen values of matrix 2
 EigResult(eigenvalues=array([-0.21110255, 14.21110255]), eigenvectors=matrix([[-0.75499722, -0.54580557],
        [ 0.65572799, -0.83791185]]))
